name = "api-server"
main = "worker/index.ts"
compatibility_date = "2025-10-25"

[vars]
ENVIRONMENT = "development"

# Add your KV Namespaces, Durable Objects, or other bindings here if needed
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxx"

[dev]
port = 8787
local_protocol = "http"